"""add church configuration

Revision ID: 6a1564825233
Revises: 90b9a54c04fb
Create Date: 2026-08-25 10:04:22.065052
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6a1564825233'
down_revision: str | None = '90b9a54c04fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "branches",
        sa.Column(
            "denomination",
            sa.String(length=120),
            nullable=True,
        ),
    )

    op.add_column(
        "branches",
        sa.Column(
            "default_language",
            sa.String(length=10),
            nullable=False,
            server_default="en",
        ),
    )

    op.add_column(
        "branches",
        sa.Column(
            "timezone",
            sa.String(length=80),
            nullable=False,
            server_default="Africa/Dar_es_Salaam",
        ),
    )

    op.add_column(
        "branches",
        sa.Column(
            "community_label",
            sa.String(length=120),
            nullable=False,
            server_default="Community Group",
        ),
    )

    op.alter_column(
        "branches",
        "default_language",
        server_default=None,
    )

    op.alter_column(
        "branches",
        "timezone",
        server_default=None,
    )

    op.alter_column(
        "branches",
        "community_label",
        server_default=None,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'community_label')
    op.drop_column('branches', 'timezone')
    op.drop_column('branches', 'default_language')
    op.drop_column('branches', 'denomination')
    # ### end Alembic commands ###

