"""add community groups

Revision ID: 90b9a54c04fb
Revises: fc41793146bf
Create Date: 2026-08-21 18:58:39.952694
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '90b9a54c04fb'
down_revision: str | None = 'fc41793146bf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "community_groups",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("group_type", sa.String(length=80), nullable=False),
        sa.Column("leader_member_id", sa.Uuid(), nullable=True),
        sa.Column("area", sa.String(length=120), nullable=True),
        sa.Column("meeting_day", sa.String(length=40), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
            name=op.f(
                "fk_community_groups_branch_id_branches"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["leader_member_id"],
            ["members.id"],
            name=op.f(
                "fk_community_groups_leader_member_id_members"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_community_groups"),
        ),
    )

    op.create_table(
        "community_group_memberships",
        sa.Column(
            "community_group_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "member_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.String(length=40),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=40),
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["community_group_id"],
            ["community_groups.id"],
            name=op.f(
                "fk_community_group_memberships_"
                "community_group_id_community_groups"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
            name=op.f(
                "fk_community_group_memberships_"
                "member_id_members"
            ),
        ),
        sa.UniqueConstraint(
            "community_group_id",
            "member_id",
            name="uq_community_group_membership_member",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f(
                "pk_community_group_memberships"
            ),
        ),
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community_group_memberships')
    op.drop_table('community_groups')
    # ### end Alembic commands ###

