"""add attendance session state

Revision ID: aea540d28d3e
Revises: 60d8f54791c2
Create Date: 2026-08-08 09:32:45.780806
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'aea540d28d3e'
down_revision: str | None = '60d8f54791c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    op.add_column(
        "events",
        sa.Column(
            "attendance_status",
            sa.String(length=20),
            nullable=False,
            server_default="scheduled",
        ),
    )

    op.add_column(
        "events",
        sa.Column(
            "attendance_opened_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.add_column(
        "events",
        sa.Column(
            "attendance_closed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.alter_column(
        "events",
        "attendance_status",
        server_default=None,
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'attendance_closed_at')
    op.drop_column('events', 'attendance_opened_at')
    op.drop_column('events', 'attendance_status')
    # ### end Alembic commands ###

