"""add ministry memberships

Revision ID: d685ae3baed4
Revises: 6a1564825233
Create Date: 2026-08-27 09:02:51.538151
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd685ae3baed4'
down_revision: str | None = '6a1564825233'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ministry_memberships',
    sa.Column('ministry_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_ministry_memberships_member_id_members')),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], name=op.f('fk_ministry_memberships_ministry_id_ministries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministry_memberships')),
    sa.UniqueConstraint('ministry_id', 'member_id', name='uq_ministry_membership_member')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ministry_memberships')
    # ### end Alembic commands ###

