"""expand people profile fields

Revision ID: f242871e3d4a
Revises: aea540d28d3e
Create Date: 2026-08-20 09:57:17.608592
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f242871e3d4a'
down_revision: str | None = 'aea540d28d3e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('household_people', sa.Column('gender', sa.String(length=40), nullable=True))
    op.add_column('household_people', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('household_people', sa.Column('preferred_language', sa.String(length=10), nullable=True))
    op.add_column('members', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('members', sa.Column('area', sa.String(length=120), nullable=True))
    op.add_column('members', sa.Column('gender', sa.String(length=40), nullable=True))
    op.add_column('members', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('marital_status', sa.String(length=40), nullable=True))
    op.add_column('members', sa.Column('occupation', sa.String(length=120), nullable=True))
    op.add_column('members', sa.Column('preferred_language', sa.String(length=10), nullable=True))
    op.add_column('members', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('visitors', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('visitors', sa.Column('area', sa.String(length=120), nullable=True))
    op.add_column('visitors', sa.Column('gender', sa.String(length=40), nullable=True))
    op.add_column('visitors', sa.Column('preferred_language', sa.String(length=10), nullable=True))
    op.add_column('visitors', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitors', 'notes')
    op.drop_column('visitors', 'preferred_language')
    op.drop_column('visitors', 'gender')
    op.drop_column('visitors', 'area')
    op.drop_column('visitors', 'address')
    op.drop_column('members', 'notes')
    op.drop_column('members', 'preferred_language')
    op.drop_column('members', 'occupation')
    op.drop_column('members', 'marital_status')
    op.drop_column('members', 'date_of_birth')
    op.drop_column('members', 'gender')
    op.drop_column('members', 'area')
    op.drop_column('members', 'address')
    op.drop_column('household_people', 'preferred_language')
    op.drop_column('household_people', 'date_of_birth')
    op.drop_column('household_people', 'gender')
    # ### end Alembic commands ###

