"""add household contribution support

Revision ID: fc41793146bf
Revises: f242871e3d4a
Create Date: 2026-08-21 10:36:01.585255
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fc41793146bf'
down_revision: str | None = 'f242871e3d4a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    op.add_column(
        "contributions",
        sa.Column(
            "household_id",
            sa.Uuid(),
            nullable=True,
        ),
    )

    op.add_column(
        "contributions",
        sa.Column(
            "contributor_scope",
            sa.String(length=20),
            nullable=False,
            server_default="individual",
        ),
    )

    op.create_foreign_key(
        op.f("fk_contributions_household_id_households"),
        "contributions",
        "households",
        ["household_id"],
        ["id"],
    )

    op.alter_column(
        "contributions",
        "contributor_scope",
        server_default=None,
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_contributions_household_id_households'), 'contributions', type_='foreignkey')
    op.drop_column('contributions', 'contributor_scope')
    op.drop_column('contributions', 'household_id')
    # ### end Alembic commands ###

